### ISSUE TITLE
account transactions GET request shows wrong data

### ISSUE THREAD

**Issue by woelkjulian** [ChristianNorbertBraun/seaweed-banking#2]
Created accounts and transaction successfully

with request :
http://localhost:3333/accounts/{bic}/{iban} 

account info is shown correctly with the transaction and correct balance:

<img width="423" alt="accountinfo" src="https://cloud.githubusercontent.com/assets/25659642/23554211/67022596-0024-11e7-8569-930f72fb83c8.png">

with request for transactions of the same account:
http://localhost:3333/accounts/{bic}/{iban}/transactions

the response with transaction data is for every account: 

<img width="422" alt="transactions" src="https://cloud.githubusercontent.com/assets/25659642/23554244/8e93fd28-0024-11e7-81fd-00791e88832e.png">

**Comment by ChristianNorbertBraun** [comment]
Should be fixed. The account info is now returned at the endpoint `http://localhost:3333/accounts/{bic}/{iban}/transactions` and should therefore look like this:
```
{
  "iban": "DE306410695947278512",
  "bic": "281ELDIJEW8",
  "balance": 8636,
  "transactions": [
    {
      "iban": "DE306410695947278512",
      "bic": "281ELDIJEW8",
      "bookingDate": "2017-03-08T21:19:45.140179331Z",
      "currency": "EUR",
      "valueInSmallestUnit": 74,
      "intendedUse": "testingTransactions"
    }
  ]
}
```
